development:
  adapter: mysql2
  encoding: utf8
  database: naalloy
  username: naalloy
  password: chab-wa-ru-fim 
  host: ganon.imagemanagement.com

production:
  adapter: mysql2
  encoding: utf8
  database: naalloy
  username: naalloy
  password: chab-wa-ru-fim 
  host: ganon.imagemanagement.com
