development:
  adapter: mysql2
  encoding: utf8
  database: naalloy
  username: naalloy
  password: quy-byfu-wi-zu
  host: ganon.imagemanagement.com 

test:
  adapter: mysql2
  encoding: utf8
  database: naalloy
  username: naalloy
  password: quy-byfu-wi-zu
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: naalloy
  username: naalloy
  password: quy-byfu-wi-zu
  host: ganon.imagemanagement.com
