development:
  adapter: mysql2
  encoding: utf8
  database: dust-3
  username: root
  password: 
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: 
  username: 
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: 
  username: 
  password: 
  host: ganon.imagemanagement.com
