development:
  adapter: mysql2
  encoding: utf8
  database: forward
  username: forward
  password: f9g8aght4kjfgi
  host: ganon.imagemanagement.com 

test:
  adapter: mysql2
  encoding: utf8
  database: forward
  username: forward
  password: f9g8aght4kjfgi
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: forward
  username: forward
  password: f9g8aght4kjfgi
  host: ganon.imagemanagement.com